export const GET_ALLTASKS_LOADING = "GET_ALLTASKS_LOADING";
export const GET_ALLTASKS_SUCCESS = "GET_ALLTASKS_SUCCESS";
export const GET_ALLTASKS_FAILED = "GET_ALLTASKS_FAILED"
export const SAVE_SCENARIO = "SAVE_SCENARIO"
export const SAVE_SCRIPT = "SAVE_SCRIPT"

export const GET_RECIPIENTS_LOADING = "GET_RECIPIENTS_LOADING";
export const GET_RECIPIENTS_SUCCESS = "GET_RECIPIENTS_SUCCESS";
export const GET_RECIPIENTS_FAILED = "GET_RECIPIENTS_FAILED";

export const GET_SCRIPT_FIELD_LOADING = "GET_SCRIPT_FIELD_LOADING";
export const GET_SCRIPT_FIELD_SUCCESS = "GET_SCRIPT_FIELD_SUCCESS";
export const GET_SCRIPT_FIELD_FAILED = "GET_SCRIPT_FIELD_FAILED";

export const POST_TASK_LOADING = "POST_TASK_LOADING";
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS";
export const POST_TASK_FAILED = "POST_TASK_FAILED";

export const GET_GALLERY_LOADING = "GET_GALLERY_LOADING";
export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const GET_GALLERY_FAILED = "GET_GALLERY_FAILED";

export const GET_COMMENTS_LOADING = "GET_COMMENTS_LOADING";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILED = "GET_COMMENTS_FAILED";

export const ADD_COMMENT_LOADING = "ADD_COMMENT_LOADING";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const GET_TASKASSIGNMENT_LOADING = "GET_TASKASSIGNMENT_LOADING";
export const GET_TASKASSIGNMENT_SUCCESS = "GET_TASKASSIGNMENT_SUCCESS";
export const GET_TASKASSIGNMENT_FAILED = "GET_TASKASSIGNMENT_FAILED";
export const GET_TASKASSIGNMENT_CLEAR = "GET_TASKASSIGNMENT_CLEAR";

export const POST_VIDEOREHEARSAL_LOADING = "POST_VIDEOREHEARSAL_LOADING";
export const POST_VIDEOREHEARSAL_SUCCESS = "POST_VIDEOREHEARSAL_SUCCESS";
export const POST_VIDEOREHEARSAL_FAILED = "POST_VIDEOREHEARSAL_FAILED";

export const UPDATE_TASK_LOADING = "UPDATE_TASK_LOADING";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILED = "UPDATE_TASK_FAILED";

export const GET_FEEDBACKS_LOADING = "GET_FEEDBACKS_LOADING";
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS";
export const GET_FEEDBACKS_FAILED = "GET_FEEDBACKS_FAILED";

export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const IS_LIKE_GALLERY = "IS_LIKE_GALLERY"
export const IS_LIKE_GALLERY_SUCCESS = "IS_LIKE_GALLERY_SUCCESS"
export const IS_LIKE_GALLERY_FAILED = "IS_LIKE_GALLERY_FAILED"

export const SELECTED_GALLERY = "SELECTED_GALLERY"

export const GET_KEYWORDS_LOADING = "GET_KEYWORDS_LOADING";
export const GET_KEYWORDS_SUCCESS = "GET_KEYWORDS_SUCCESS";
export const GET_KEYWORDS_FAILED = "GET_KEYWORDS_FAILED";

export const DELETE_COMMENT_LOADING = "DELETE_COMMENT_LOADING";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED";

export const GET_TAG_USERS_LOADING = "GET_TAG_USERS_LOADING";
export const GET_TAG_USERS_SUCCESS = "GET_TAG_USERS_SUCCESS";
export const GET_TAG_USERS_FAILED = "GET_TAG_USERS_FAILED";

export const POST_SHARE_LOADING = "POST_SHARE_LOADING";
export const POST_SHARE_SUCCESS = "POST_SHARE_SUCCESS";
export const POST_SHARE_FAILED = "POST_SHARE_FAILED";

export const CLEAR_TASK = "CLEAR_TASK"
